baseURL: https://trebllaw.github.io
title: "trebllaw"
languageCode: en-us

module:
   imports:
   - path: github.com/hugo-toha/toha/v4
   mounts:
   - source: static/files
     target: static/files
   - source: ./node_modules/flag-icon-css/flags
     target: static/flags
   - source: ./node_modules/@fontsource/mulish/files
     target: static/files
   - source: ./node_modules/katex/dist/fonts
     target: static/fonts

languages:
   en:
      languageName: English
      weight: 1

outputs:
   home:
      - HTML
      - RSS
      - JSON

enableEmoji: true

params:
   background: "images/background.jpg"
   
   logo:
      main: images/main-logo.png
      inverted: images/inverted-logo.png
      favicon: images/favicon.png
   
   gitRepo: https://github.com/trebllaw/trebllaw.github.io
   gitBranch: source
   
   features:
      darkMode:
        enable: true
      
   tags:
      enable: true
      on_card: true
      
   embedpdf:
      enable: true

   footer:
      enable: false